version: "3.1"

services:
  sink:
    build: ./with-events-sink
    ports:
      - 8888:8888
    links:
      - mongodb
      - kafka


  source:
    build: ./with-events-source
    ports:
      - 8080:8080
    links:
      - kafka

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  zookeeper:
    image: debezium/zookeeper:0.8
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:0.8
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
